### ISSUE TITLE
能请问下，这个（4328, 3960）坐标是怎么计算出来的啊，或者说我要写这个脚本，怎样获取这个坐标呢

### ISSUE THREAD

**Issue by 1357214904** [babalae/bettergi-scripts#1]
await captureCrystalfly('枫丹-塔拉塔海谷', 4328, 3960, 4);

**Comment by huiyadanli** [comment]
下个版本会有快捷键，直接在大地图上获取。

或者直接在下面图片上找对应传送点的坐标：

![5 0全地图+传送点_压缩](https://github.com/user-attachments/assets/b4d1ec8b-7022-4fc7-b814-e1ba694efcbc)

**Comment by 1357214904** [comment]
图有点模糊，能发我邮箱不，非常感谢。 1357214904@qq.com
我也加了这个894935931群，麻烦也帮我通过一下，非常感谢。

**Comment by huiyadanli** [comment]
https://wwmy.lanzouq.com/iOXq7296wt4d

**Comment by emako** [comment]
这个图不是内置BGI？

**Comment by huiyadanli** [comment]
> 这个图不是内置BGI？

内置了小图和特征点，原图 200M。。

**Comment by huiyadanli** [comment]
下载链接更新
https://wwmy.lanzouq.com/b0fosbd9g
密码:coco
