### ISSUE TITLE
脚本回放常见问题合集

### ISSUE THREAD

**Issue by HZYgrandma** [babalae/bettergi-scripts#2]
0.在反馈问题时候请确保你使用的是最新版BGI，反馈问题时请带上录屏

1.执行脚本时发生异常：Error：当前不在地图界面？
请确保你打开地图的按键是M键

2.运行脚本时候方向有较大偏差？
i）请确保游戏以60帧运行
ii）请确保游戏灵敏度保持默认

3.传送完成后角色站在原地不动？
请确保游戏左上角派蒙头像未被其他悬浮窗遮挡

4.运行晶蝶脚本时传送过去晶蝶已经飞走了？
请确保队伍中带有早柚/瑶瑶

5.运行狗粮脚本时会差一点距离，或者走过头？
请确保运行时是琳妮特前台且拥有双风共鸣（元素共鸣需要四个角色组队触发，只带两个风系角色是没用的），且队伍中没有其他移速天赋加成的角色

6.晶蝶抓不齐/狗粮没调查到/调查了不捡？
自动晶蝶和自动狗粮没有任何图像识别，无法保证百分百获取

**Comment by huiyadanli** [comment]
## 常见问题

* 执行脚本时直接发生异常：Error：当前不在地图界面
  * 请确保你打开地图的按键是M键
* 传送完成后角色站在原地不动？
  * 请确保游戏左上角派蒙头像未被其他悬浮窗遮挡
* 运行键鼠脚本时候方向有较大偏差？(自动采集晶蝶/自动狗粮)
  * 请确保游戏以60帧运行
  * 请确保游戏视角灵敏度保持默认（默认值是3）
* 运行自动晶蝶脚本时传送过去晶蝶已经飞走了？(自动采集晶蝶)
  * 请确保队伍中带有早柚/瑶瑶
* 运行狗粮脚本时会差一点距离，或者走过头？(自动狗粮)
  * 请确保运行时是琳妮特前台且拥有双风共鸣（元素共鸣需要四个角色组队触发，只带两个风系角色是没用的），且队伍中没有其他移速天赋加成的角色
* 晶蝶抓不齐/狗粮没调查到/调查了不捡？
  * 自动晶蝶和自动狗粮在走到目的地时没有任何图像识别，无法保证百分百获取

**Comment by huiyadanli** [comment]
感恩，已经更新到文档与站点中
